version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
     # - TZ=Asia/Yekaterinburg
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
     # - TZ=Asia/Yekaterinburg
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=OrDer$P@$$
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
     # - TZ=Asia/Yekaterinburg
      - POSTGRES_PASSWORD=OrDer$P@$$
      - POSTGRES_USER=admin
      - POSTGRES_DB=shareit